"""tambah created_at ke notifikasi

Revision ID: 03104c8a82a6
Revises: 17d0767f716a
Create Date: 2026-05-29 22:10:04.698585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03104c8a82a6'
down_revision: Union[str, None] = '17d0767f716a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
