"""tambah dosen pembimbing ke mahasiswa

Revision ID: 17d0767f716a
Revises: 93a1ab872e1d
Create Date: 2026-05-29 21:54:53.562931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d0767f716a'
down_revision: Union[str, None] = '93a1ab872e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahasiswa', sa.Column('dosen_pembimbing_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mahasiswa', 'dosen', ['dosen_pembimbing_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mahasiswa', type_='foreignkey')
    op.drop_column('mahasiswa', 'dosen_pembimbing_id')
    # ### end Alembic commands ###
