"""tambah tanggal_pengajuan ke surat_rekomendasi

Revision ID: 19c241a036e6
Revises: 03104c8a82a6
Create Date: 2026-05-30 15:12:46.560465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c241a036e6'
down_revision: Union[str, None] = '03104c8a82a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surat_rekomendasi', sa.Column('tanggal_pengajuan', sa.Date(), nullable=False, server_default=sa.func.current_date()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surat_rekomendasi', 'tanggal_pengajuan')
    # ### end Alembic commands ###
