"""tambah field surat_rekomendasi ke pendaftaran

Revision ID: 32c88f9d9b3d
Revises: f0b5b22b2ad4
Create Date: 2026-05-11 09:24:49.284115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c88f9d9b3d'
down_revision: Union[str, None] = 'f0b5b22b2ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logbook', sa.Column('keterangan', sa.String(), nullable=False))
    op.drop_column('logbook', 'keterangann')
    op.add_column('pendaftaran', sa.Column('dokumen_surat_rekomendasi', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pendaftaran', 'dokumen_surat_rekomendasi')
    op.add_column('logbook', sa.Column('keterangann', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('logbook', 'keterangan')
    # ### end Alembic commands ###
