"""Initial migration create all tables

Revision ID: 8fbe28c2a8d7
Revises: 
Create Date: 2026-04-27 21:50:17.656742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fbe28c2a8d7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lowongan',
    sa.Column('id_lowongan', sa.Integer(), nullable=False),
    sa.Column('judul', sa.String(), nullable=False),
    sa.Column('deskripsi', sa.String(), nullable=False),
    sa.Column('persyaratan', sa.String(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_lowongan')
    )
    op.create_index(op.f('ix_lowongan_id_lowongan'), 'lowongan', ['id_lowongan'], unique=False)
    op.create_index(op.f('ix_lowongan_judul'), 'lowongan', ['judul'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dosen',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_dosen_nip'), 'dosen', ['nip'], unique=True)
    op.create_table('mahasiswa',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(), nullable=False),
    sa.Column('prodi', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_mahasiswa_nim'), 'mahasiswa', ['nim'], unique=True)
    op.create_table('staff',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_nip'), 'staff', ['nip'], unique=True)
    op.create_table('laporan',
    sa.Column('id_laporan', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.Column('dosen_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('nilai', sa.Integer(), nullable=True),
    sa.Column('tanggal_lapor', sa.Date(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('dokumen_laporan', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dosen_id'], ['dosen.user_id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.user_id'], ),
    sa.PrimaryKeyConstraint('id_laporan')
    )
    op.create_index(op.f('ix_laporan_id_laporan'), 'laporan', ['id_laporan'], unique=False)
    op.create_table('logbook',
    sa.Column('id_logbook', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.Column('tgl_log', sa.Date(), nullable=True),
    sa.Column('kegiatan', sa.String(), nullable=False),
    sa.Column('kendala', sa.String(), nullable=True),
    sa.Column('status_verifikasi', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.user_id'], ),
    sa.PrimaryKeyConstraint('id_logbook')
    )
    op.create_index(op.f('ix_logbook_id_logbook'), 'logbook', ['id_logbook'], unique=False)
    op.create_table('pendaftaran',
    sa.Column('id_pendaftaran', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.Column('lowongan_id', sa.Integer(), nullable=False),
    sa.Column('tgl_daftar', sa.Date(), nullable=True),
    sa.Column('dokumen_cv', sa.String(), nullable=False),
    sa.Column('status_seleksi', sa.Boolean(), nullable=True),
    sa.Column('keterangan', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lowongan_id'], ['lowongan.id_lowongan'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.user_id'], ),
    sa.PrimaryKeyConstraint('id_pendaftaran')
    )
    op.create_index(op.f('ix_pendaftaran_id_pendaftaran'), 'pendaftaran', ['id_pendaftaran'], unique=False)
    op.create_table('surat_rekomendasi',
    sa.Column('id_surat', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.Column('dosen_id', sa.Integer(), nullable=False),
    sa.Column('isi_surat', sa.String(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dosen_id'], ['dosen.user_id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.user_id'], ),
    sa.PrimaryKeyConstraint('id_surat')
    )
    op.create_index(op.f('ix_surat_rekomendasi_id_surat'), 'surat_rekomendasi', ['id_surat'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surat_rekomendasi_id_surat'), table_name='surat_rekomendasi')
    op.drop_table('surat_rekomendasi')
    op.drop_index(op.f('ix_pendaftaran_id_pendaftaran'), table_name='pendaftaran')
    op.drop_table('pendaftaran')
    op.drop_index(op.f('ix_logbook_id_logbook'), table_name='logbook')
    op.drop_table('logbook')
    op.drop_index(op.f('ix_laporan_id_laporan'), table_name='laporan')
    op.drop_table('laporan')
    op.drop_index(op.f('ix_staff_nip'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_mahasiswa_nim'), table_name='mahasiswa')
    op.drop_table('mahasiswa')
    op.drop_index(op.f('ix_dosen_nip'), table_name='dosen')
    op.drop_table('dosen')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lowongan_judul'), table_name='lowongan')
    op.drop_index(op.f('ix_lowongan_id_lowongan'), table_name='lowongan')
    op.drop_table('lowongan')
    # ### end Alembic commands ###
