"""integrasi logbook ke laporan dan penyesuaian model

Revision ID: 93a1ab872e1d
Revises: 77cceca53d33
Create Date: 2026-05-18 23:47:32.488541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93a1ab872e1d'
down_revision: Union[str, None] = '77cceca53d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laporan', sa.Column('lowongan_id', sa.Integer(), nullable=True))
    op.alter_column('laporan', 'dokumen_laporan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'laporan', 'lowongan', ['lowongan_id'], ['lowongan_id'])
    op.alter_column('logbook', 'waktu_mulai',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('logbook', 'waktu_selesai',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('logbook', 'durasi_kegiatan',
               existing_type=postgresql.INTERVAL(),
               nullable=True)
    op.alter_column('logbook', 'keterangan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('logbook', 'jenis_kegiatan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logbook', 'jenis_kegiatan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('logbook', 'keterangan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('logbook', 'durasi_kegiatan',
               existing_type=postgresql.INTERVAL(),
               nullable=False)
    op.alter_column('logbook', 'waktu_selesai',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('logbook', 'waktu_mulai',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'laporan', type_='foreignkey')
    op.alter_column('laporan', 'dokumen_laporan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('laporan', 'lowongan_id')
    # ### end Alembic commands ###
