"""ubah field surat_rekomendasi menjadi not null

Revision ID: adfbc35cb41d
Revises: 32c88f9d9b3d
Create Date: 2026-05-11 09:48:50.928179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adfbc35cb41d'
down_revision: Union[str, None] = '32c88f9d9b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pendaftaran', 'dokumen_surat_rekomendasi',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pendaftaran', 'dokumen_surat_rekomendasi',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
