"""ubah_dosen_pembimbing_menjadi_fk_di_logbook

Revision ID: d91a4b912f1f
Revises: adfbc35cb41d
Create Date: 2026-05-15 18:52:17.654009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91a4b912f1f'
down_revision: Union[str, None] = 'adfbc35cb41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logbook', sa.Column('dosen_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'logbook', 'dosen', ['dosen_id'], ['user_id'])
    op.drop_column('logbook', 'dosen_pembimbing')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logbook', sa.Column('dosen_pembimbing', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'logbook', type_='foreignkey')
    op.drop_column('logbook', 'dosen_id')
    # ### end Alembic commands ###
