"""initial migration

Revision ID: f0b5b22b2ad4
Revises: 
Create Date: 2026-05-04 21:31:20.623673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f0b5b22b2ad4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lowongan',
    sa.Column('lowongan_id', sa.Integer(), nullable=False),
    sa.Column('perusahaan', sa.String(), nullable=False),
    sa.Column('judul_posisi', sa.String(), nullable=False),
    sa.Column('deskripsi_pekerjaan', sa.String(), nullable=False),
    sa.Column('kualifikasi', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('lowongan_id')
    )
    op.create_index(op.f('ix_lowongan_judul_posisi'), 'lowongan', ['judul_posisi'], unique=False)
    op.create_index(op.f('ix_lowongan_lowongan_id'), 'lowongan', ['lowongan_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dosen',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_dosen_nip'), 'dosen', ['nip'], unique=True)
    op.create_table('mahasiswa',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(), nullable=False),
    sa.Column('fakultas', sa.String(), nullable=False),
    sa.Column('prodi', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_mahasiswa_nim'), 'mahasiswa', ['nim'], unique=True)
    op.create_table('notifikasi',
    sa.Column('notifikasi_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('isi_notifikasi', sa.String(), nullable=False),
    sa.Column('target_url', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notifikasi_id')
    )
    op.create_index(op.f('ix_notifikasi_notifikasi_id'), 'notifikasi', ['notifikasi_id'], unique=False)
    op.create_table('staff',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_nip'), 'staff', ['nip'], unique=True)
    op.create_table('laporan',
    sa.Column('laporan_id', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.Column('dosen_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('nilai', sa.Integer(), nullable=True),
    sa.Column('tanggal_lapor', sa.Date(), nullable=True),
    sa.Column('catatan', sa.String(), nullable=True),
    sa.Column('dokumen_laporan', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dosen_id'], ['dosen.user_id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.user_id'], ),
    sa.PrimaryKeyConstraint('laporan_id')
    )
    op.create_index(op.f('ix_laporan_laporan_id'), 'laporan', ['laporan_id'], unique=False)
    op.create_table('pendaftaran',
    sa.Column('pendaftaran_id', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.Column('lowongan_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_daftar', sa.Date(), nullable=True),
    sa.Column('dokumen_cv', sa.String(), nullable=False),
    sa.Column('status_seleksi', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lowongan_id'], ['lowongan.lowongan_id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.user_id'], ),
    sa.PrimaryKeyConstraint('pendaftaran_id')
    )
    op.create_index(op.f('ix_pendaftaran_pendaftaran_id'), 'pendaftaran', ['pendaftaran_id'], unique=False)
    op.create_table('surat_rekomendasi',
    sa.Column('surat_id', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.Column('dosen_id', sa.Integer(), nullable=False),
    sa.Column('dokumen_surat', sa.String(), nullable=False),
    sa.Column('status_surat', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dosen_id'], ['dosen.user_id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.user_id'], ),
    sa.PrimaryKeyConstraint('surat_id')
    )
    op.create_index(op.f('ix_surat_rekomendasi_surat_id'), 'surat_rekomendasi', ['surat_id'], unique=False)
    op.create_table('logbook',
    sa.Column('logbook_id', sa.Integer(), nullable=False),
    sa.Column('laporan_id', sa.Integer(), nullable=False),
    sa.Column('mahasiswa_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_log', sa.Date(), nullable=True),
    sa.Column('waktu_mulai', sa.DateTime(), nullable=False),
    sa.Column('waktu_selesai', sa.DateTime(), nullable=False),
    sa.Column('durasi_kegiatan', sa.Interval(), nullable=False),
    sa.Column('dosen_pembimbing', sa.String(), nullable=False),
    sa.Column('keterangann', sa.String(), nullable=False),
    sa.Column('media', sa.String(), nullable=True),
    sa.Column('dokumentasi', sa.String(), nullable=True),
    sa.Column('jenis_kegiatan', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['laporan_id'], ['laporan.laporan_id'], ),
    sa.ForeignKeyConstraint(['mahasiswa_id'], ['mahasiswa.user_id'], ),
    sa.PrimaryKeyConstraint('logbook_id')
    )
    op.create_index(op.f('ix_logbook_logbook_id'), 'logbook', ['logbook_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logbook_logbook_id'), table_name='logbook')
    op.drop_table('logbook')
    op.drop_index(op.f('ix_surat_rekomendasi_surat_id'), table_name='surat_rekomendasi')
    op.drop_table('surat_rekomendasi')
    op.drop_index(op.f('ix_pendaftaran_pendaftaran_id'), table_name='pendaftaran')
    op.drop_table('pendaftaran')
    op.drop_index(op.f('ix_laporan_laporan_id'), table_name='laporan')
    op.drop_table('laporan')
    op.drop_index(op.f('ix_staff_nip'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_notifikasi_notifikasi_id'), table_name='notifikasi')
    op.drop_table('notifikasi')
    op.drop_index(op.f('ix_mahasiswa_nim'), table_name='mahasiswa')
    op.drop_table('mahasiswa')
    op.drop_index(op.f('ix_dosen_nip'), table_name='dosen')
    op.drop_table('dosen')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_lowongan_lowongan_id'), table_name='lowongan')
    op.drop_index(op.f('ix_lowongan_judul_posisi'), table_name='lowongan')
    op.drop_table('lowongan')
    # ### end Alembic commands ###
